spring.application.name=blog
spring.profiles.active=dev

jwt.secret=${JWT_SECRET:bXktMjU2LWJpdC1zZWNyZXQta2V5LWhlcmUtbWFrZS1pdC1hdC1sZWFzdC0zMi1ieXRlcy1sb25n}
jwt.access-token-expiration=${JWT_ACCESS_EXPIRATION:900000}
jwt.refresh-token-expiration=${JWT_REFRESH_EXPIRATION:86400000}

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=changemeinprod!
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
# Kafka
spring.kafka.bootstrap-servers=localhost:9092
logging.level.org.springframework.kafka=DEBUG
# Email
spring.mail.host=localhost
spring.mail.port=1025