spring.config.activate.on-profile=dev

# Logging
logging.level.com.universalis.blog.security=DEBUG
logging.level.org.springframework.security=DEBUG
# Database
spring.jpa.show-sql=true
# Email
spring.mail.host=localhost
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false